name: Build
on:
  workflow_dispatch:

jobs:
  build_sdk:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [clientsdk, dedicated, gamesdk, tools\naveditor, tools\netconsole, tools\sdklauncher]
    steps:
      - name: Setup MSBuild Dependency
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
          msbuild-architecture: x64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for commits within the last 24 hours
        uses: AlexHolderDeveloper/CommitsWithinTime@v1.1.5
        id: commits
        with:
          hours: 24

      - name: Set Variables
        id: vars
        run: |
          echo SHA7=$(git rev-parse --short HEAD) >> $env:GITHUB_ENV
          echo ::set-output name=continue::true

      - name: Build Project
        run: msbuild .\r5sdk.sln /m /target:${{ matrix.target }} /p:configuration=Release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            game/**/*.exe
            game/**/*.dll